<?php

  $stmtlistApt = $sql->Execute($sql->Prepare("SELECT AR_CODE, AR_PROPERTY_NAME, AR_PROPERTY_ID,AR_CLIENT_NAME, AR_CLIENT_ID, AR_CLIENT_CONTACT, AR_CLIENT_EMAIL, AR_DURATION, AR_PAYMENT_DATE, AR_APARTMENT_NUMBER,AR_CHECKING_OUT_DATE, AR_TOTAL_COST,AR_TOTAL_PAYMENT,AR_BALANCE, AR_STATUS FROM rent_tb ORDER BY 'AR_CHECKING_OUT_DATE' ASC
     LIMIT 5"),array());
    print $sql->ErrorMsg();

$stmtlistLand = $sql->Execute($sql->Prepare("SELECT LS_CODE, LS_PROPERTY_NAME, LS_PROPERTY_ID,LS_CLIENT_NAME, LS_CLIENT_ID, LS_CLIENT_CONTACT, LS_CLIENT_EMAIL, LS_NUM_OF_PLOT, LS_PLOT_NUMBER, LS_PAYMENT_TERM,LS_TOTAL_COST,LS_TOTAL_PAYMENT,LS_BALANCE,LS_NEXT_PAY_DATE, LS_STATUS FROM land_sale_tb WHERE LS_STATUS IN ('1','2','3') AND LS_BALANCE > 0 ORDER BY 'LS_NEXT_PAY_DATE' ASC LIMIT 5"),array());
  print $sql->ErrorMsg();		

  
  $stmtPayList = $sql->Execute($sql->Prepare("SELECT ALT_CODE, ALT_PAYMENT_ID, ALT_PROPERTY_NAME, ALT_PROPERTY_ID, ALT_CLIENT_NAME, ALT_CLIENT_ID, ALT_PROPERTY_TYPE, ALT_TOTAL_COST, ALT_TOTAL_PAYMENT, ALT_BALANCE,ALT_PAY_DATE FROM all_transactions_tb WHERE ALT_PROPERTY_ID = ".$sql->Param('1')." AND ALT_STATUS IN ('1', '2', '3') "),array($keys));
  print $sql->ErrorMsg();
  
    